import type { ProjectConfig } from "../types/project";

export const projects = [
  {
    slug: "mazey",
    name: "Mazey",
    category: "npm",
    repository: "chengchuu/mazey",
    packageName: "mazey",
    description: "A practical JavaScript and TypeScript utility library.",
    status: "active",
    featured: true,
    home: "https://chengchuu.github.io/mazey/",
    playground: "https://chengchuu.github.io/mazey/playground/",
    github: "https://github.com/chengchuu/mazey",
    npm: "https://www.npmjs.com/package/mazey",
    api: "https://chengchuu.github.io/mazey/api/",
  },
  {
    slug: "mazey-wechat-launch-app",
    name: "WeChat Launch App",
    category: "npm",
    repository: "chengchuu/mazey-wechat-launch-app",
    packageName: "mazey-wechat-launch-app",
    status: "active",
    home: "https://chengchuu.github.io/mazey-wechat-launch-app/",
    playground: "https://chengchuu.github.io/mazey-wechat-launch-app/playground/",
    api: "https://chengchuu.github.io/mazey-wechat-launch-app/api/",
    github: "https://github.com/chengchuu/mazey-wechat-launch-app",
    npm: "https://www.npmjs.com/package/mazey-wechat-launch-app",
  },
  {
    slug: "mazey-taro-utils",
    name: "Taro Utils",
    category: "npm",
    repository: "chengchuu/mazey-taro-utils",
    packageName: "mazey-taro-utils",
    status: "active",
    home: "https://chengchuu.github.io/mazey-taro-utils/",
    playground: "https://chengchuu.github.io/mazey-taro-utils/playground/",
    api: "https://chengchuu.github.io/mazey-taro-utils/api/",
    github: "https://github.com/chengchuu/mazey-taro-utils",
    npm: "https://www.npmjs.com/package/mazey-taro-utils",
  },
  {
    slug: "aliyunoss-cli",
    name: "Aliyun OSS CLI",
    category: "npm",
    repository: "chengchuu/aliyunoss-cli",
    packageName: "aliyunoss-cli",
    status: "active",
    home: "https://chengchuu.github.io/aliyunoss-cli/",
    examples: "https://chengchuu.github.io/aliyunoss-cli/examples/",
    api: "https://chengchuu.github.io/aliyunoss-cli/api/",
    github: "https://github.com/chengchuu/aliyunoss-cli",
    npm: "https://www.npmjs.com/package/aliyunoss-cli",
  },
  {
    slug: "mazey-lazy-load-images",
    name: "Lazy Load Images",
    category: "npm",
    repository: "chengchuu/mazey-lazy-load-images",
    packageName: "mazey-lazy-load-images",
    status: "active",
    home: "https://chengchuu.github.io/mazey-lazy-load-images/",
    playground: "https://chengchuu.github.io/mazey-lazy-load-images/playground/",
    github: "https://github.com/chengchuu/mazey-lazy-load-images",
    npm: "https://www.npmjs.com/package/mazey-lazy-load-images",
    api: "https://chengchuu.github.io/mazey-lazy-load-images/api/",
  },
  {
    slug: "mazey-wordpress-utils",
    name: "WordPress Utils",
    category: "npm",
    repository: "chengchuu/mazey-wordpress-utils",
    packageName: "mazey-wordpress-utils",
    status: "active",
    home: "https://chengchuu.github.io/mazey-wordpress-utils/",
    playground: "https://chengchuu.github.io/mazey-wordpress-utils/playground/",
    api: "https://chengchuu.github.io/mazey-wordpress-utils/api/",
    github: "https://github.com/chengchuu/mazey-wordpress-utils",
    npm: "https://www.npmjs.com/package/mazey-wordpress-utils",
  },
  {
    slug: "layer-esm",
    name: "Layer ESM",
    category: "npm",
    repository: "chengchuu/layer-esm",
    packageName: "layer-esm",
    status: "active",
    home: "https://chengchuu.github.io/layer-esm/",
    playground: "https://chengchuu.github.io/layer-esm/playground/",
    api: "https://chengchuu.github.io/layer-esm/api/",
    github: "https://github.com/chengchuu/layer-esm",
    npm: "https://www.npmjs.com/package/layer-esm",
  },
  {
    slug: "mazey-dayspan-vuetify",
    name: "Dayspan Vuetify",
    category: "npm",
    repository: "chengchuu/mazey-dayspan-vuetify",
    packageName: "mazey-dayspan-vuetify",
    hideFromProfileReadme: true,
    status: "active",
    playground: "https://chengchuu.github.io/mazey-dayspan-vuetify/",
    github: "https://github.com/chengchuu/mazey-dayspan-vuetify",
    npm: "https://www.npmjs.com/package/mazey-dayspan-vuetify",
  },
  {
    slug: "mazey-element-ui",
    name: "Element UI",
    category: "npm",
    repository: "chengchuu/mazey-element-ui",
    packageName: "mazey-element-ui",
    hideFromProfileReadme: true,
    status: "active",
    home: "https://chengchuu.github.io/mazey-element-ui/",
    github: "https://github.com/chengchuu/mazey-element-ui",
    npm: "https://www.npmjs.com/package/mazey-element-ui",
  },
  {
    slug: "scp-next",
    name: "SCP Next",
    category: "npm",
    repository: "chengchuu/scp-next",
    packageName: "scp-next",
    status: "active",
    home: "https://chengchuu.github.io/scp-next/",
    examples: "https://chengchuu.github.io/scp-next/examples/",
    api: "https://chengchuu.github.io/scp-next/api/",
    github: "https://github.com/chengchuu/scp-next",
    npm: "https://www.npmjs.com/package/scp-next",
  },
  {
    slug: "vue-screenfull",
    name: "Vue Screenfull",
    category: "npm",
    repository: "chengchuu/vue-screenfull",
    packageName: "vue-screenfull",
    status: "active",
    home: "https://chengchuu.github.io/vue-screenfull/",
    playground: "https://chengchuu.github.io/vue-screenfull/playground/",
    api: "https://chengchuu.github.io/vue-screenfull/api/",
    github: "https://github.com/chengchuu/vue-screenfull",
    npm: "https://www.npmjs.com/package/vue-screenfull",
  },
  {
    slug: "gurl",
    name: "GURL",
    category: "go",
    repository: "chengchuu/gurl",
    modulePath: "github.com/chengchuu/gurl",
    status: "active",
    home: "https://chengchuu.github.io/gurl/",
    examples: "https://chengchuu.github.io/gurl/examples/",
    api: "https://chengchuu.github.io/gurl/api/",
    github: "https://github.com/chengchuu/gurl",
  },
  {
    slug: "asiatz",
    name: "AsiaTZ",
    category: "go",
    repository: "chengchuu/asiatz",
    modulePath: "github.com/chengchuu/asiatz",
    status: "active",
    featured: true,
    home: "https://chengchuu.github.io/asiatz/",
    examples: "https://chengchuu.github.io/asiatz/examples/",
    github: "https://github.com/chengchuu/asiatz",
    api: "https://chengchuu.github.io/asiatz/api/",
  },
  {
    slug: "vue-china-map",
    name: "vue-china-map",
    category: "github",
    repository: "chengchuu/vue-china-map",
    description: "A Vue China map visualization powered by Vite and ECharts.",
    status: "active",
    demo: "https://chengchuu.github.io/vue-china-map/",
    github: "https://github.com/chengchuu/vue-china-map",
  },
  {
    slug: "bootstrap-blueprints",
    name: "bootstrap-blueprints",
    category: "github",
    repository: "chengchuu/bootstrap-blueprints",
    description: "Standalone Bootstrap 3 learning examples.",
    status: "active",
    home: "https://i.mazey.net/bootstrap-blueprints/",
    github: "https://github.com/chengchuu/bootstrap-blueprints",
  },
] as const satisfies readonly ProjectConfig[];
