import type { ProjectConfig } from "../types/project";

export const projects = [
  {
    slug: "mazey",
    name: "Mazey",
    category: "npm",
    repository: "chengchuu/mazey",
    packageName: "mazey",
    description: "A practical JavaScript and TypeScript utility library.",
    status: "active",
    featured: true,
    home: "https://chengchuu.github.io/mazey/",
    playground: "https://chengchuu.github.io/mazey/playground/",
    github: "https://github.com/chengchuu/mazey",
    npm: "https://www.npmjs.com/package/mazey",
    api: "https://chengchuu.github.io/mazey/api/",
  },
  {
    slug: "mazey-wechat-launch-app",
    name: "WeChat Launch App",
    category: "npm",
    repository: "chengchuu/mazey-wechat-launch-app",
    packageName: "mazey-wechat-launch-app",
    status: "active",
    github: "https://github.com/chengchuu/mazey-wechat-launch-app",
    npm: "https://www.npmjs.com/package/mazey-wechat-launch-app",
  },
  {
    slug: "mazey-taro-utils",
    name: "Taro Utils",
    category: "npm",
    repository: "chengchuu/mazey-taro-utils",
    packageName: "mazey-taro-utils",
    status: "active",
    github: "https://github.com/chengchuu/mazey-taro-utils",
    npm: "https://www.npmjs.com/package/mazey-taro-utils",
  },
  {
    slug: "aliyunoss-cli",
    name: "Aliyun OSS CLI",
    category: "npm",
    repository: "chengchuu/aliyunoss-cli",
    packageName: "aliyunoss-cli",
    status: "active",
    github: "https://github.com/chengchuu/aliyunoss-cli",
    npm: "https://www.npmjs.com/package/aliyunoss-cli",
  },
  {
    slug: "mazey-lazy-load-images",
    name: "Lazy Load Images",
    category: "npm",
    repository: "chengchuu/mazey-lazy-load-images",
    packageName: "mazey-lazy-load-images",
    status: "active",
    github: "https://github.com/chengchuu/mazey-lazy-load-images",
    npm: "https://www.npmjs.com/package/mazey-lazy-load-images",
  },
  {
    slug: "mazey-wordpress-utils",
    name: "WordPress Utils",
    category: "npm",
    repository: "chengchuu/mazey-wordpress-utils",
    packageName: "mazey-wordpress-utils",
    status: "active",
    github: "https://github.com/chengchuu/mazey-wordpress-utils",
    npm: "https://www.npmjs.com/package/mazey-wordpress-utils",
  },
  {
    slug: "gurl",
    name: "GURL",
    category: "go",
    repository: "chengchuu/gurl",
    modulePath: "github.com/chengchuu/gurl",
    status: "active",
    github: "https://github.com/chengchuu/gurl",
  },
  {
    slug: "asiatz",
    name: "AsiaTZ",
    category: "go",
    repository: "chengchuu/asiatz",
    modulePath: "github.com/chengchuu/asiatz",
    status: "active",
    featured: true,
    home: "https://chengchuu.github.io/asiatz/",
    examples: "https://chengchuu.github.io/asiatz/examples/",
    github: "https://github.com/chengchuu/asiatz",
    api: "https://chengchuu.github.io/asiatz/api/",
  },
] as const satisfies readonly ProjectConfig[];
